"""initial accounts schema

Revision ID: 0d558214a2cb
Revises:
Create Date: 2026-09-04 22:01:32.105771
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d558214a2cb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth2_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("launch_uri", sa.Text(), nullable=False),
        sa.Column("backchannel_logout_uri", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=True),
        sa.Column("client_secret", sa.String(length=120), nullable=True),
        sa.Column("client_id_issued_at", sa.Integer(), nullable=False),
        sa.Column("client_secret_expires_at", sa.Integer(), nullable=False),
        sa.Column("client_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_oauth2_clients_client_id"), "oauth2_clients", ["client_id"], unique=False
    )
    op.create_table(
        "rate_limit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=192), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rate_limit_lookup",
        "rate_limit_events",
        ["action", "subject", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("username_key", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system_admin", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("terms_accepted_at", sa.DateTime(), nullable=True),
        sa.Column("merged_into_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_into_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_sub"), "users", ["sub"], unique=True)
    op.create_index(op.f("ix_users_username_key"), "users", ["username_key"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_target_user_id"), "audit_logs", ["target_user_id"], unique=False
    )
    op.create_table(
        "backchannel_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=False),
        sa.Column("sid", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backchannel_jobs_client_id"), "backchannel_jobs", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_backchannel_jobs_next_attempt_at"),
        "backchannel_jobs",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backchannel_jobs_user_id"), "backchannel_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "legacy_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_app", sa.String(length=32), nullable=False),
        sa.Column("source_user_id", sa.String(length=64), nullable=False),
        sa.Column("login_alias_key", sa.String(length=128), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_app", "source_user_id"),
    )
    op.create_index(
        op.f("ix_legacy_credentials_login_alias_key"),
        "legacy_credentials",
        ["login_alias_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legacy_credentials_user_id"), "legacy_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "login_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column("alias_key", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_aliases_alias_key"), "login_aliases", ["alias_key"], unique=True)
    op.create_index(op.f("ix_login_aliases_user_id"), "login_aliases", ["user_id"], unique=False)
    op.create_table(
        "oauth2_authorization_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=True),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("response_type", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("nonce", sa.Text(), nullable=True),
        sa.Column("auth_time", sa.Integer(), nullable=False),
        sa.Column("acr", sa.Text(), nullable=True),
        sa.Column("amr", sa.Text(), nullable=True),
        sa.Column("code_challenge", sa.Text(), nullable=True),
        sa.Column("code_challenge_method", sa.String(length=48), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_oauth2_authorization_codes_user_id"),
        "oauth2_authorization_codes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "oauth2_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=True),
        sa.Column("token_type", sa.String(length=40), nullable=True),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.Integer(), nullable=False),
        sa.Column("access_token_revoked_at", sa.Integer(), nullable=False),
        sa.Column("refresh_token_revoked_at", sa.Integer(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
    )
    op.create_index(
        op.f("ix_oauth2_tokens_refresh_token"), "oauth2_tokens", ["refresh_token"], unique=False
    )
    op.create_index(op.f("ix_oauth2_tokens_sid"), "oauth2_tokens", ["sid"], unique=False)
    op.create_index(op.f("ix_oauth2_tokens_user_id"), "oauth2_tokens", ["user_id"], unique=False)
    op.create_table(
        "user_app_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=False),
        sa.Column("first_authorized_at", sa.DateTime(), nullable=False),
        sa.Column("last_authorized_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "client_id"),
    )
    op.create_index(
        op.f("ix_user_app_memberships_client_id"),
        "user_app_memberships",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_app_memberships_user_id"), "user_app_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "web_sessions",
        sa.Column("sid", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("csrf_token", sa.String(length=96), nullable=False),
        sa.Column("auth_time", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.create_index(op.f("ix_web_sessions_token_hash"), "web_sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_web_sessions_user_id"), "web_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_web_sessions_user_id"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_token_hash"), table_name="web_sessions")
    op.drop_table("web_sessions")
    op.drop_index(op.f("ix_user_app_memberships_user_id"), table_name="user_app_memberships")
    op.drop_index(op.f("ix_user_app_memberships_client_id"), table_name="user_app_memberships")
    op.drop_table("user_app_memberships")
    op.drop_index(op.f("ix_oauth2_tokens_user_id"), table_name="oauth2_tokens")
    op.drop_index(op.f("ix_oauth2_tokens_sid"), table_name="oauth2_tokens")
    op.drop_index(op.f("ix_oauth2_tokens_refresh_token"), table_name="oauth2_tokens")
    op.drop_table("oauth2_tokens")
    op.drop_index(
        op.f("ix_oauth2_authorization_codes_user_id"), table_name="oauth2_authorization_codes"
    )
    op.drop_table("oauth2_authorization_codes")
    op.drop_index(op.f("ix_login_aliases_user_id"), table_name="login_aliases")
    op.drop_index(op.f("ix_login_aliases_alias_key"), table_name="login_aliases")
    op.drop_table("login_aliases")
    op.drop_index(op.f("ix_legacy_credentials_user_id"), table_name="legacy_credentials")
    op.drop_index(op.f("ix_legacy_credentials_login_alias_key"), table_name="legacy_credentials")
    op.drop_table("legacy_credentials")
    op.drop_index(op.f("ix_backchannel_jobs_user_id"), table_name="backchannel_jobs")
    op.drop_index(op.f("ix_backchannel_jobs_next_attempt_at"), table_name="backchannel_jobs")
    op.drop_index(op.f("ix_backchannel_jobs_client_id"), table_name="backchannel_jobs")
    op.drop_table("backchannel_jobs")
    op.drop_index(op.f("ix_audit_logs_target_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username_key"), table_name="users")
    op.drop_index(op.f("ix_users_sub"), table_name="users")
    op.drop_table("users")
    op.drop_index("idx_rate_limit_lookup", table_name="rate_limit_events")
    op.drop_table("rate_limit_events")
    op.drop_index(op.f("ix_oauth2_clients_client_id"), table_name="oauth2_clients")
    op.drop_table("oauth2_clients")
    # ### end Alembic commands ###
